# Netlify Configuration for Farid Cadet Academy Frontend

[build]
  command = "npm run build"
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "18"

# Environment variables (set these in Netlify dashboard)
 VITE_SUPABASE_URL = https://husfemrigonousvtuyvf.supabase.co
 VITE_SUPABASE_KEY = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh1c2ZlbXJpZ29ub3VzdnR1eXZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk5OTYxMjAsImV4cCI6MjA3NTU3MjEyMH0.0imHOgQzLen4KfZ_L_i_tvzsj0phRwpES4oceZq2GXE
 VITE_API_URL = https://fca-3oz1.onrender.com

# Redirect all routes to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
