# Netlify Configuration for Farid Cadet Academy Frontend

[build]
  command = "npm run build"
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "18"

# Environment variables must be set in Netlify dashboard UI:
# Site configuration -> Environment variables -> Add variable
# Required variables:
#   VITE_SUPABASE_URL = https://husfemrigonousvtuyvf.supabase.co
#   VITE_SUPABASE_KEY = (your supabase anon key)
#   VITE_API_URL = https://fca-3oz1.onrender.com

# Redirect all routes to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security and performance headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://husfemrigonousvtuyvf.supabase.co https://fca-3oz1.onrender.com; frame-ancestors 'none';"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# API proxy for local development
[[redirects]]
  from = "/api/*"
  to = "https://fca-3oz1.onrender.com/api/:splat"
  status = 200
  force = true
  headers = {X-Forwarded-Host = "farid-cadet.netlify.app"}

# Security.txt
[[redirects]]
  from = "/.well-known/security.txt"
  to = "/security.txt"
  status = 200

# Preload fonts
[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Content-Type = "font/woff2"