services:
  - type: web
    name: farid-cadet-academy-backend
    env: node
    plan: free
    # Backend only - frontend is deployed separately on Netlify
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: farid-cadet-academy-backend
          property: port
      - key: JWT_SECRET
        generateValue: true
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://farid-cadet.netlify.app
    # Health check configuration
    healthCheckPath: /api/health
    # Auto-deploy configuration
    autoDeploy: true
    # Environment-specific settings
    envSpecificConfig:
      - environment: production
        envVars:
          - key: LOG_LEVEL
            value: info
          - key: ENABLE_CORS
            value: true