services:
  - type: web
    name: farid-cadet-academy-backend
    env: node
    plan: standard
    runtime: node-18
    buildCommand: npm install
    startCommand: npm start
    
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        generateValue: true
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: REDIS_URL
        sync: false
      - key: FRONTEND_URL
        value: https://farid-cadet.vercel.app
      - key: LOG_LEVEL
        value: info
      - key: CORS_ORIGIN
        value: https://farid-cadet.vercel.app
    
    healthCheckPath: /api/health
    healthCheckInterval: 30
    
    autoDeploy: true
    
    disk:
      name: logs
      mountPath: /app/logs
      sizeGB: 1